/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.comapping.android.controller;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int Button01=0x7f05000c;
        public static final int EditText01=0x7f05000b;
        public static final int TableLayout01=0x7f050001;
        public static final int TableRow01=0x7f050002;
        public static final int TableRow02=0x7f050005;
        public static final int TextView01=0x7f050003;
        public static final int TextView02=0x7f050006;
        public static final int TextView03=0x7f050000;
        public static final int email=0x7f050004;
        public static final int error=0x7f050009;
        public static final int login=0x7f050008;
        public static final int metaMapHeader=0x7f05000a;
        public static final int metaMapText=0x7f05000d;
        public static final int password=0x7f050007;
    }
    public static final class layout {
        public static final int login=0x7f030000;
        public static final int metamap=0x7f030001;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
    }
}
