/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.comapping.android.controller;

public final class R {
    public static final class array {
        public static final int view_types=0x7f040000;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int attachment=0x7f020000;
        public static final int clear_cache_menu_icon=0x7f020001;
        public static final int flag_carefull=0x7f020002;
        public static final int flag_caution=0x7f020003;
        public static final int flag_for_discussion=0x7f020004;
        public static final int flag_go=0x7f020005;
        public static final int flag_possibility=0x7f020006;
        public static final int flag_progress=0x7f020007;
        public static final int flag_risk=0x7f020008;
        public static final int folder_icon=0x7f020009;
        public static final int home_button=0x7f02000a;
        public static final int home_button_grey=0x7f02000b;
        public static final int icon=0x7f02000c;
        public static final int icon_bomb=0x7f02000d;
        public static final int icon_clock=0x7f02000e;
        public static final int icon_dollar=0x7f02000f;
        public static final int icon_exclamation_mark=0x7f020010;
        public static final int icon_heart=0x7f020011;
        public static final int icon_magnifier=0x7f020012;
        public static final int icon_question_mark=0x7f020013;
        public static final int icon_thumbs_down=0x7f020014;
        public static final int icon_thumbs_up=0x7f020015;
        public static final int internet_icon=0x7f020016;
        public static final int logout_menu_icon=0x7f020017;
        public static final int map_icon=0x7f020018;
        public static final int metamap=0x7f020019;
        public static final int preferences_menu_icon=0x7f02001a;
        public static final int priority1=0x7f02001b;
        public static final int priority2=0x7f02001c;
        public static final int priority3=0x7f02001d;
        public static final int priority4=0x7f02001e;
        public static final int priority5=0x7f02001f;
        public static final int priority6=0x7f020020;
        public static final int priority7=0x7f020021;
        public static final int priority8=0x7f020022;
        public static final int priority9=0x7f020023;
        public static final int reload_metamap_menu_icon=0x7f020024;
        public static final int sdcard_icon=0x7f020025;
        public static final int smiley_furious=0x7f020026;
        public static final int smiley_happy=0x7f020027;
        public static final int smiley_normal=0x7f020028;
        public static final int smiley_sad=0x7f020029;
        public static final int task_completion_25=0x7f02002a;
        public static final int task_completion_50=0x7f02002b;
        public static final int task_completion_75=0x7f02002c;
        public static final int task_completion_complete=0x7f02002d;
        public static final int task_completion_todo=0x7f02002e;
        public static final int up_level_button=0x7f02002f;
        public static final int up_level_button_grey=0x7f020030;
    }
    public static final class id {
        public static final int CheckBox01=0x7f070009;
        public static final int MapView=0x7f07000c;
        public static final int RelativeLayout01=0x7f070008;
        public static final int TableLayout01=0x7f070001;
        public static final int TableRow01=0x7f070002;
        public static final int TableRow02=0x7f070005;
        public static final int TextView01=0x7f070003;
        public static final int TextView02=0x7f070006;
        public static final int TextView03=0x7f070000;
        public static final int Zoom=0x7f07000d;
        public static final int description=0x7f070016;
        public static final int email=0x7f070004;
        public static final int error=0x7f07000b;
        public static final int homeButton=0x7f070010;
        public static final int icon=0x7f070014;
        public static final int listView=0x7f070013;
        public static final int login=0x7f07000a;
        public static final int logout=0x7f07001d;
        public static final int mapSynchronizeButton=0x7f070018;
        public static final int metaMapButtons=0x7f07000e;
        public static final int name=0x7f070015;
        public static final int openFolder=0x7f070019;
        public static final int openWithExplorerView=0x7f07001a;
        public static final int openWithTreeView=0x7f07001b;
        public static final int password=0x7f070007;
        public static final int preferences=0x7f07001c;
        public static final int synchronizeButton=0x7f070011;
        public static final int upLevelButton=0x7f07000f;
        public static final int viewSwitcher=0x7f070012;
        public static final int zoom=0x7f070017;
    }
    public static final class layout {
        public static final int login=0x7f030000;
        public static final int map=0x7f030001;
        public static final int metamap=0x7f030002;
        public static final int preferences=0x7f030003;
        public static final int row=0x7f030004;
    }
    public static final class menu {
        public static final int map_options=0x7f060000;
        public static final int metamap_folder_context=0x7f060001;
        public static final int metamap_map_context=0x7f060002;
        public static final int metamap_options=0x7f060003;
    }
    public static final class string {
        public static final int app_name=0x7f050000;
        public static final int explorer_view_value=0x7f050003;
        public static final int tree_view_value=0x7f050004;
        public static final int view_type_preference_key=0x7f050001;
        public static final int view_type_preference_title=0x7f050002;
    }
}
