/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.comapping.android.controller;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int happy=0x7f020000;
        public static final int icon=0x7f020001;
        public static final int metamap=0x7f020002;
        public static final int p1=0x7f020003;
        public static final int p2=0x7f020004;
        public static final int p3=0x7f020005;
        public static final int p4=0x7f020006;
        public static final int to_do=0x7f020007;
    }
    public static final class id {
        public static final int CheckBox01=0x7f050009;
        public static final int EditText01=0x7f05000d;
        public static final int Loading=0x7f050012;
        public static final int RelativeLayout01=0x7f050008;
        public static final int TableLayout01=0x7f050001;
        public static final int TableRow01=0x7f050002;
        public static final int TableRow02=0x7f050005;
        public static final int TextView01=0x7f050003;
        public static final int TextView02=0x7f050006;
        public static final int TextView03=0x7f050000;
        public static final int email=0x7f050004;
        public static final int error=0x7f05000b;
        public static final int loadExplorerView=0x7f05000f;
        public static final int loadTreeView=0x7f05000e;
        public static final int login=0x7f05000a;
        public static final int logout=0x7f050010;
        public static final int metaMapHeader=0x7f05000c;
        public static final int metaMapText=0x7f050011;
        public static final int password=0x7f050007;
    }
    public static final class layout {
        public static final int login=0x7f030000;
        public static final int metamap=0x7f030001;
        public static final int splash=0x7f030002;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
    }
}
